### PR TITLE
Added note about ACM.

### PR DESCRIPTION
**Pull request by bonibruno**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lkdavies** [comment]
Thank you for your pull request. A member of the team will review it and will provide updates here about progress.

**Comment by lkdavies** [comment]
Thanks for your pull request. I think this is important enough to merit a note at the beginning of the topic. I've made a few small changes to align the text with AWS Style guidelines. Let me know if you this change looks good to you, and I'll merge the PR.

**Comment by bonibruno** [comment]
Yes, this looks good Liz, please merge.

**Review by bonibruno — COMMENTED** [review]
Yes this looks good Liz, please merge.

**Comment by lkdavies** [comment]
I've merged your request. Thank you for your contribution!

**Pull request merged**
